In [1]:
import numpy as np

a = np.random.randn(5)    ## içinde 5 gauss değişkeni olan bir a dizisi
print(a)

[-2.32029188  0.64329439  0.29246949 -1.10727299 -1.28172435]


In [2]:
print(a.shape)   ## a'nın şekli 5 e tanımlandı

(5,)


In [3]:
print(a.T)     ## a'nın devriği olan transpose(T) yazdırmak ise a ile aynı.

[-2.32029188  0.64329439  0.29246949 -1.10727299 -1.28172435]


In [5]:
print(np.dot(a,a.T))  ##a ve a'nın devriğinin skaler çarpımı(dış çarpım) matris beklenirken tek bir sayı olabilir

8.751991290332041


In [6]:
a = np.random.randn(5,1)  ##tanım a'yı (5,1) boyutunda bir sütun vektörü yapar.Eğer nöral ağlarda çalışmak istiyorsak.
print(a)

[[-1.20566544]
 [ 0.37715969]
 [-1.27447133]
 [ 0.995033  ]
 [ 0.33481981]]


In [7]:
print(a.T)   ##şimdi bir satır vektörü oldu 

[[-1.20566544  0.37715969 -1.27447133  0.995033    0.33481981]]


In [8]:
print(np.dot(a,a.T))  ## asıl şimdi vektörün skaler çarpımı bize matrisi verdi.

[[ 1.45362914 -0.4547284   1.53658603 -1.1996769  -0.40368067]
 [-0.4547284   0.14224943 -0.48067921  0.37528634  0.12628054]
 [ 1.53658603 -0.48067921  1.62427717 -1.26814103 -0.42671825]
 [-1.1996769   0.37528634 -1.26814103  0.99009067  0.33315676]
 [-0.40368067  0.12628054 -0.42671825  0.33315676  0.11210431]]


In [12]:
assert(a.shape == (5,1))